config/routes.rb
Rails.application.routes.draw do

  root 'jobs#index'

  get 'login', :to => 'access#login'
  post 'access/attempt_login'
  get 'logout', :to =>'access#logout'

  get 'static_pages/about'

  resources :jobs

  resources :users do
    member do
      get 'posts'
      get 'delete'
    end
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base

  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates_formatting_of :email

end

app/models/job.rb
class Job < ActiveRecord::Base

  belongs_to :user

  validates :title, presence: true
  validates :company, presence: true
  validates :location, presence: true
  validates :url, presence: true, uniqueness: true
  #validates_formatting_of :url
  validates :category, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_secure_password
  
  has_many :jobs
  
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates_formatting_of :email
  
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  def login
  end
  
  def attempt_login
    if params[:email].present? && params[:password].present?
      found_user = User.where(:email => params[:email]).first
      
      if found_user
        auth_user = found_user.authenticate(params[:password])
      end
    end
    
    if auth_user
      session[:user_id] = auth_user.id
      session[:email] = auth_user.email
      flash[:notice] = "Log-in Successfull"
      redirect_to(:controller => "users", :action => "show", :id => auth_user.id)
    else
      flash[:notice] = "Invalid username/password combination."
      redirect_to(:action => "login")
    end
  end
  
  def logout      
    session[:user_id] = nil
    session[:email] = nil
    flash[:notice] = "Logged Out"
    redirect_to(:action => "login")
  end
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_action :confirm_access, :only => [:edit, :update]

  def index
    @jobs = Job.order("created_at DESC").page(params[:page]).per(10)
    @user_id = session[:user_id]
    if session[:user_id] != nil
      @is_admin = User.find(session[:user_id]).admin
    else
      @is_admin = false
    end
  end

  def new
    @job = Job.new
  end

  def create
      @job = Job.new(job_params)

      if verify_recaptcha(:model => @job, :message => "Are you human?")
        @job.user_id = session[:user_id]
        if @job.save
          flash[:notice] = "Creation Successful"
          redirect_to root_path
        else
          render 'new'
        end
      else
        render 'new'
      end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])

    if @job.update_attributes(job_params)
      flash[:notice] = "Update Successful"
      redirect_to(:controller => "users", :action => "posts", :id => @job.user_id)
    else
      render 'edit'
    end
  end

  def destroy
    job = Job.find(params[:id])
    job.destroy
    redirect_to(:controller => "jobs", :action => "index")
  end

  private
    def job_params
      params.require(:job).permit(:title, :company, :url, :category, :description, :location, :user_id)
    end

    def confirm_access
      @job = Job.find(params[:id])
      #debugger

      if session[:user_id] == nil
        flash[:notice] = "Please log in"
        redirect_to(:controller => "access", :action => "login")
        return false
      end

      if User.find(session[:user_id]).admin == true
        return true
      end

      if @job.user_id.to_i == session[:user_id]
        return true
      end

      flash[:notice] = "You do not have access to do that"
      redirect_to(root_path)

      return false

    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :confirm_access, :except => [:new, :create]
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def posts
    @jobs = Job.where(:user_id => params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if verify_recaptcha(:model => @user, :message => "Are you human?")
      if @user.save
        flash[:notice] = "Registration Successful"
        redirect_to(:controller => "access", :action => "login")
      else
        render 'new'
      end
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    
    if @user.update_attributes(user_params)
      flash[:notice] = "Update Successful"
      redirect_to(:controller => "users", :action => "show", :id => @user.id)
    else
      render 'edit'
    end
    
  end

  def delete
    @user = User.find(params[:id])
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    
    flash[:notice] = "#{user.name} Deleted"
    redirect_to(:controller => "users", :action => "index")
  end
  
  private 
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
  
    def confirm_access
      #debugger

      if session[:user_id] == nil
        flash[:notice] = "Please log in"
        redirect_to(:controller => "access", :action => "login")
        return false
      end

      if User.find(session[:user_id]).admin == true
        return true
      end

      if params[:id].to_i == session[:user_id]
        return true
      end

      flash[:notice] = "You do not have access to do that"
      redirect_to(root_path)

      return false

    end
  
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def render_errors(object)
    render(partial: "shared/errors", locals: {:object =>  object})
  end

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/access/login.html.erb
<% @page_title="Login" %>

  <div class="card white">

    <div class="card-content">
      <p>Not already a member? <%= link_to "Sign Up Here", :controller => "users", :action => "new" %></p>

      <%= form_tag(:action => "attempt_login") do %>

        <div class="row">
          <div class="col s10">
            <%= label_tag(:email)  %><br />
            <%= text_field_tag(:email) %>
          </div>
        </div>

        <div class="row">
          <div class="col s10">
            <%= label_tag(:password)  %><br />
            <%= password_field_tag(:password) %>
          </div>
        </div>

        <div class="row">
          <div class="col">
            <%= submit_tag "Login", class: "btn blue-grey white-text", type: "submit" %>
          </div>
        </div>
    </div>
</div>

<% end %>

app/views/jobs/_form.html.erb
<%= render_errors(@job) %>

<div class="row">
  <%= f.label :title, class: 'col control-label' %>
  <div class="col-sm-10">
    <%= f.text_field :title, class: 'form-control' %>
  </div>
</div>
<div class="row">
  <%= f.label :company, class: 'col control-label' %>
  <div class="col-sm-10">
    <%= f.text_field :company, class: 'form-control' %>
  </div>
</div>
<div class="row">
  <%= f.label :url, class: 'col control-label' %>
  <div class="col-sm-10">
    <%= f.text_field :url, class: 'form-control' %>
  </div>
</div>
<div class="row">
  <%= f.label :location, class: 'col control-label' %>
  <div class="col-sm-10">
    <%= f.text_field :location, class: 'form-control' %>
  </div>
</div>
<div class="row">
  <%= f.label :category, class: 'col control-label' %>
  <div>
    <br />
    <%= f.radio_button(:category, 1) %>
    <%= f.label(:category_1, "Job") %>
    <br />
    <%= f.radio_button(:category, 2) %>
    <%= f.label(:category_2, "Internship") %>
  </div>
</div>
<div class="row">
  <%= f.label :description, class: 'col control-label' %>
  <div class="input-field col s12">
    <%= f.text_area :description, class: 'materialize-textarea'%>
  </div>
</div>

app/views/jobs/_navigation.html.erb
<header>
  <div class="navbar-fixed">
    <nav class="blue-grey darken-2">
      <div class="nav-wrapper container">
        <ul id="nav-mobile" class="right">
          <li><%= link_to "Browse", :action => "index" %></li>
          <li><%= link_to "Post", :action => "new" %></li>
          <li><%= link_to "About", :controller => "static_pages", :action => "about" %></li>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/jobs/edit.html.erb
<% @page_title="Edit Job" %>

<%= form_for(@job, :url => {:action => "update", :id => @job.id}) do |f| %>
  <div class="card white">

    <div class="card-content">

      <%= render partial: "form", locals: {:job => @job, :f => f} %>

      <div class="row">
        <div class="col">
          <%= f.submit "Submit Job", class: "btn blue-grey white-text", type: "submit" %>
        </div>
      </div>
    </div>
</div>

<% end %>

app/views/jobs/index.html.erb
<% @page_title="All Jobs" %>

<% @jobs.each do |job| %>
  <div class="card white">

    <div class="card-content">
      <% if @is_admin %>
        <%= link_to "Delete", job, :method => :delete %>
        <br />
      <% end %>
      <span class="right-align"><%= job.created_at.to_date %></span> <br />
      <span class="card-title"><%= link_to job.title, job.url, :target => "_blank" %></span><br />
      <% if job.category == 1 %>
        Job
      <% else %>
        Internship
      <% end %> <br />
      <%= job.company %> <br />
      <%= job.location %> <br /><br />
      <%= job.description %>
    </div>

    <div class="card-action">
       <%= link_to "Click Here To Apply", job.url, :target => "_blank" %>
    </div>

  </div>

  <p><%= paginate @jobs %></p>

<% end %>

app/views/jobs/new.html.erb
<% @page_title="New Job" %>

<%= form_for(@job) do |f| %>
  <div class="card white">

    <div class="card-content">

      <%= render partial: "form", locals: {:job => @job, :f => f} %>

      <div class="row">
        <%= recaptcha_tags %>
      </div>

      <div class="row">
        <div class="col">
          <%= f.submit "Submit Job", class: "btn blue-grey white-text", type: "submit" %>
        </div>
      </div>
    </div>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Will Code For Food - <%= @page_title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta id="viewport" name="viewport" content="width=device-width; initial-scale=1; maximum-scale=1; user-scalable=0;" />
</head>
<body class="grey lighten-4">

  <%= render partial: "shared/navigation" %>

  <main>
    <div id="container" class="container">

      <div class="row">
        <%= render partial: "shared/left_sidebar" %>

        <div id="rightSidebar" class="col l8 m7 s12 offset-m5 offset-l4">

          <%= render partial: "shared/warning" %>

          <%= render partial: "shared/flash" %>

          <%= yield %>
        </div>
      </div>
    </div>
  </main>

<%= debug(params) if Rails.env.development? %>

<script>
  $(document).ready(function() {
    $('select').material_select();
  });
</script>


</body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <strong><%= pluralize(object.errors.count, "error") %> prohibited this record from being saved:</strong>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if !flash[:notice].blank? %>
<div class="flash">
  <%= flash[:notice] %>
</div>
<% end %>

app/views/shared/_left_sidebar.html.erb
<div id="leftSidebar" class="col l3 m4 hide-on-small-only">
  <h4><span class="line">Will Code</span> <span class="line"> For Food</span></h4>
    <p>
      Great Coding jobs<br />
      No experience required.<br />
      <br/>

      Free to Search<br />
      Free to Post<br />
      <em>Premium Posts Coming Soon</em></p>
    <p>
      <%= link_to "Post A Job", new_job_path, class: "btn blue-grey white-text"%></p>
</div>

app/views/shared/_navigation.html.erb
<header>
  <div class="navbar-fixed">
    <nav class="blue-grey darken-2">
      <div class="nav-wrapper container">
        <ul id="nav-mobile" class="right">
          <li><%= link_to "Jobs", :controller => "jobs", :action => "index" %></li>
          <li><%= link_to "Post", :controller => "jobs", :action => "new" %></li>
          <% if session[:user_id] == nil %>
            <li><%= link_to "Login", :controller => "access", :action => "login" %></li>
          <% else %>
            <li><%= link_to "Admin", :controller => "users", :action => "show", :id => session[:user_id] %></li>
            <li><%= link_to "Logout", :controller => "access", :action => "logout" %></li>
          <% end %>
          <li><%= link_to "About", :controller => "static_pages", :action => "about" %></li>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/shared/_warning.html.erb
<p>WARNING: Site is still in beta, database may be cleared at any time.</p>

app/views/static_pages/about.html.erb
<% @page_title="Abouts" %>

  <div class="card white">

    <div class="card-content">
    <p>Tired of searching through hundreds of job postings just to find ones for 'junior' candidates?</p>
    <p>Tired of seeing that most of those positions for 'junior' candidates want 3-5 years of experience in 4 different stacks, some of which
    aren't even 3 years old?</p>
    <p>Well so was I. So after another particularly frustrating evening of job hunting, I came up with the idea for this site. Grabbed the domain
    and got to work. The 1.0 version of this site was just a quick thing I threw up using WordPress. This is the 2.0 version that I've built
    from scratch using Rails. It's a little barebones right now, but I plan to keep working on and expanding it every chance I get!</p>

    <p>Questions? Feedback? <a href="https://twitter.com/wcffjobs">Drop me a message and let me know!</a></p>

    </div>
</div>

app/views/users/_form.html.erb
<%= render_errors(@user) %>

<div class="row">
  <%= f.label :name, class: 'col control-label' %>
  <div class="col-sm-10">
    <%= f.text_field :name, class: 'form-control' %>
  </div>
</div>
<div class="row">
  <%= f.label :email, class: 'col control-label' %>
  <div class="col-sm-10">
    <%= f.text_field :email, class: 'form-control' %>
  </div>
</div>
<div class="row">
  <%= f.label :password, class: 'col control-label' %>
  <div class="col-sm-10">
    <%= f.password_field :password, class: 'form-control' %>
  </div>
</div>
<div class="row">
  <%= f.label :password_confirmation, class: 'col control-label' %>
  <div class="col-sm-10">
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
</div>

app/views/users/delete.html.erb
<% @page_title="Delete User" %>
<%= render partial: "shared/navigation" %>

<main>
  <div id="container" class="container">

    <div class="row">
      <%= render partial: "shared/left_sidebar" %>

            <div id="rightSidebar" class="col l6 m7 s12 offset-m5 offset-l6">

              <%= render partial: "shared/warning" %>
              <%= form_for(@user, :url => {:action => 'destroy', :id => @user.id}, method: 'delete' ) do |f| %>
              
              <p>Are you sure you want to delete <%= @user.name %>?</p>

          <div class="row">
            <div class="col">
              <%= f.submit "Delete", class: "btn blue-grey white-text", type: "submit" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/edit.html.erb
<% @page_title="Edit User" %>

<%= form_for(@user, :url => {:action => "update", :id => @user.id}) do |f| %>
  <div class="card white">

    <div class="card-content">
      <%= render partial: "form", locals: {:user => @user, :f => f} %>

      <div class="row">
        <div class="col">
          <%= f.submit "Submit Changes", class: "btn blue-grey white-text", type: "submit" %>
        </div>
      </div>
    </div>
</div>

<% end %>

app/views/users/index.html.erb
<% @page_title="All Users" %>
        
<% @users.each do |user| %>
<div class="card white">
  <div class="card-content">
    <%= link_to "Edit Info", {:controller => "users", :action => "edit", :id => user.id} %><br />
    <%= link_to "Delete", {:controller => "users", :action => "delete", :id => user.id} %><br />
    <span class="card-title"><%= link_to user.name, {:controller => "users", :action => "show", :id => user.id} %></span><br />
    <%= user.email %> <br />
  </div>
</div>

<% end %>

app/views/users/new.html.erb
<% @page_title="New User" %>

<%= form_for(@user) do |f| %>
  <div class="card white">

    <div class="card-content">

      <%= render partial: "form", locals: {:user => @user, :f => f} %>

      <div class="row">
        <%= recaptcha_tags %>
      </div>

      <div class="row">
        <div class="col">
          <%= f.submit "Register", class: "btn blue-grey white-text", type: "submit" %>
        </div>
      </div>
    </div>
</div>
<% end %>

app/views/users/posts.html.erb
<% @page_title="My Posts" %>

<% @jobs.each do |job| %>
  <div class="card white">

    <div class="card-content">
        <%= link_to "Delete", job, :method => :delete %>
        <br />
      <span class="right-align"><%= job.created_at.to_date %></span> <br />
      <span class="card-title"><%= link_to job.title, job.url, :target => "_blank" %></span><br />
      <% if job.category == 1 %>
        Job
      <% else %>
        Internship
      <% end %> <br />
      <%= job.company %> <br />
      <%= job.location %> <br /><br />
      <%= job.description %>
    </div>

    <div class="card-action">
      <%= link_to "Edit", :controller => "jobs", :action => "edit", :id => job.id %>
    </div>

  </div>

<% end %>

app/views/users/show.html.erb
<% @page_title="User Info" %>

<div class="card white">
  <div class="card-content user">
    <% if @user.admin == true %>
      <strong>Admin</strong><br />
    <% end %>

    <p>
      <span class="card-title blue-text text-darken-2"><%= @user.name %></span><br />
      <%= @user.email %></p>
    <p>
      <%= link_to "Edit Profile", {:controller => "users", :action => "edit", :id => @user.id} %><br />
      <%= link_to "View Posts", {:controller => "users", :action => "posts", :id => @user.id} %></p>
  </div>
</div>